### ISSUE TITLE
Client types not included

### ISSUE THREAD

**Issue by gunta** [hemengke1997/vite-plugin-i18n-detector#2]
<img width="223" alt="Screenshot 2023-12-16 at 2 41 19" src="https://github.com/hemengke1997/vite-plugin-i18n-detector/assets/657059/ccbd29d7-fbe0-44ff-b433-a49d5e5c7c10">

For some reason in the latest npm package, client types `client/index.d.ts` seem to be not included.

I'm installing it as `npm install vite-plugin-i18n-detector`

Perhaps need to use `--experimental-dts` for tsup or some other esbuild option?

**Comment by hemengke1997** [comment]
some problem occurs in CI, fixed in `2.1.2`. Thanks for your feedback!

**Comment by gunta** [comment]
Thanks!
